# Generated by Django 6.0.5 on 2026-06-12 05:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_code', models.CharField(choices=[('P1', 'Period 1 (9:00-10:00)'), ('P2', 'Period 2 (10:00-11:00)'), ('P3', 'Period 3 (11:00-12:00)'), ('P4', 'Period 4 (12:00-1:00)'), ('P5', 'Period 5 (1:30-2:30)'), ('P6', 'Period 6 (2:30-3:30)'), ('P7', 'Period 7 (3:30-4:30)'), ('P8', 'Period 8 (4:30-5:30)')], max_length=2, unique=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='attendance',
            options={'ordering': ['-date', '-period']},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='attendance',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('attendance_marked', 'Attendance Marked'), ('absent_3_days', 'Absent for 3 Consecutive Classes'), ('absent_4_days', 'Absent for 4 Consecutive Working Days'), ('low_attendance', 'Attendance Below 75%'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_marked', to='attendance.staff'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='attendance.student'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='staff',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='student',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('student', 'subject', 'date', 'period')},
        ),
    ]
