# Generated by Django 5.2.6 on 2026-06-18 05:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_attendance_change_opinion_attendance_changed_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DaySchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('department', models.CharField(max_length=100)),
                ('semester', models.IntegerField()),
                ('period', models.CharField(choices=[('P1', 'Period 1 (9:00-10:00)'), ('P2', 'Period 2 (10:00-11:00)'), ('P3', 'Period 3 (11:00-12:00)'), ('P4', 'Period 4 (12:00-1:00)'), ('P5', 'Period 5 (1:30-2:30)'), ('P6', 'Period 6 (2:30-3:30)'), ('P7', 'Period 7 (3:30-4:30)'), ('P8', 'Period 8 (4:30-5:30)')], max_length=2)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day_schedules', to='attendance.staff')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day_schedules', to='attendance.subject')),
            ],
            options={
                'ordering': ['date', 'department', 'semester', 'period'],
                'unique_together': {('date', 'department', 'semester', 'period')},
            },
        ),
        migrations.CreateModel(
            name='StaffSubjectAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=100)),
                ('semester', models.IntegerField()),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_assignments', to='attendance.staff')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_assignments', to='attendance.subject')),
            ],
            options={
                'ordering': ['department', 'semester', 'subject__subject_name'],
                'unique_together': {('staff', 'subject', 'department', 'semester')},
            },
        ),
    ]
